name: ml-base
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - xarray
  - openpyxl
  - pip
  - netCDF4
  - pip:
    - jupyter-book
    - matplotlib
    - numpy
    - ghp-import
    - wis-downloader
    - PIL